test-ranap: don't use libosmocore's tall_msgb_ctx
Use msgb_ctx from test_common.c instead, which is the same pointer after
test_common_init() ran. tall_msgb_ctx from libosmocore is no longer
getting exported since I13169c00a59fb59513dfc598de5a71d094492422.

Fix for:
  /usr/bin/ld: test-ranap.o: in function `main':
  /build/src/tests/test-ranap.c:201: undefined reference to `tall_msgb_ctx'
  /usr/bin/ld: /build/src/tests/test-ranap.c:201: undefined reference to `tall_msgb_ctx'

Change-Id: I7d0b3068760c2cd7067e2a5d929f03c7e7d1decb