tests/test-hnbap: add missing include
Fix for:
  test-hnbap.c:174:9: error: implicit declaration of function ‘ranap_set_log_area’

Change-Id: I57fe460b511bccd14e0d0d110104511292963525