tests/test-ranap: fix missing (void **) cast
Use the function like everywhere else in the code.

Fix for:
  tests/test-ranap.c:73:49: error: passing argument 3 of ‘aper_decode’ from incompatible pointer type [-Werror=incompati
ble-pointer-types]

Change-Id: I9d8a3ab70accc6a1401fe11a6d2ceef96d3b8c22