tests/hnb-test-rua: add missing include
Fix for:
  error: implicit declaration of function ‘ranap_cn_rx_co’ [-Werror=implicit-function-declaration]

Change-Id: I3dbadb63058edc990b49ec803a123292e5eea10f